/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/DefaultLayout/AppBar.vue')['default']
    AppFooter: typeof import('./src/components/DefaultLayout/AppFooter.vue')['default']
    CardSlider: typeof import('./src/components/HomePage/CardSlider.vue')['default']
    ColumnNavbar: typeof import('./src/components/DefaultLayout/ColumnNavbar.vue')['default']
    Graphok: typeof import('./src/components/GraphsComponets/Graphok.vue')['default']
    Graphz: typeof import('./src/components/GraphsComponets/Graphz.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Last: typeof import('./src/components/GraphsComponets/Last.vue')['default']
    LastTransactionsCard: typeof import('./src/components/AccountComponents/LastTransactionsCard.vue')['default']
    LoginComp: typeof import('./src/components/HardLogin/LoginComp.vue')['default']
    LoginWithMetaMask: typeof import('./src/components/AccountComponents/LoginWithMetaMask.vue')['default']
    MarketGrid: typeof import('./src/components/MarketComponent/MarketGrid.vue')['default']
    MyPropertiesCard: typeof import('./src/components/AccountComponents/MyPropertiesCard.vue')['default']
    Navbar: typeof import('./src/components/DefaultLayout/Navbar.vue')['default']
    NewUser: typeof import('./src/components/AccountComponents/NewUser.vue')['default']
    RealEstateDetails: typeof import('./src/components/MarketComponent/RealEstateDetails.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowNavbar: typeof import('./src/components/DefaultLayout/RowNavbar.vue')['default']
    SlideGroups: typeof import('./src/components/HomePage/SlideGroups.vue')['default']
    TransactionConfirmed: typeof import('./src/components/MarketComponent/TransactionConfirmed.vue')['default']
    UserInfoCard: typeof import('./src/components/AccountComponents/UserInfoCard.vue')['default']
    WalletDetailsCard: typeof import('./src/components/AccountComponents/WalletDetailsCard.vue')['default']
  }
}
