/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/account/': RouteRecordInfo<'/account/', '/account', Record<never, never>, Record<never, never>>,
    '/all-crowdfunds/': RouteRecordInfo<'/all-crowdfunds/', '/all-crowdfunds', Record<never, never>, Record<never, never>>,
    '/chatbot/': RouteRecordInfo<'/chatbot/', '/chatbot', Record<never, never>, Record<never, never>>,
    '/crowdfund-info/[address]': RouteRecordInfo<'/crowdfund-info/[address]', '/crowdfund-info/:address', { address: ParamValue<true> }, { address: ParamValue<false> }>,
    '/crowdfunding/': RouteRecordInfo<'/crowdfunding/', '/crowdfunding', Record<never, never>, Record<never, never>>,
    '/graphs/': RouteRecordInfo<'/graphs/', '/graphs', Record<never, never>, Record<never, never>>,
    '/map/': RouteRecordInfo<'/map/', '/map', Record<never, never>, Record<never, never>>,
    '/market/': RouteRecordInfo<'/market/', '/market', Record<never, never>, Record<never, never>>,
  }
}
